
language: csharp
dotnet: 1.0.4
mono: none # is not needed
dist: trusty # Ubuntu 14.04.5 image
env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
addons:  
 apt:
   packages:
   - libcurl3 # needed for 'dotnet restore'

install:
   - dotnet restore ./src/C346SpellBook_V_2.sln

script:
#    - dotnet build ./solution.sln --configuration Release
    - find . -name *.xUnitTests.csproj -exec dotnet test {} --configuration Release \; # build and run xunit tests
