language: csharp
solution: "./src/C346SpellBook_V_2.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./src/C346SpellBook_V_2.sln
script:
- xbuild ./src/C346SpellBook_V_2.sln
- mono ./Fibonacci/packages/xunit.runner.console*/tools/xunit.console.exe ./346SpellBook.Tests/UnitTest1.cs
